import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import changePasswordRouter from "./change-password";
import accountsRouter from "./accounts";
import subjectsRouter from "./subjects";
import studentsRouter from "./students";
import sessionsRouter from "./sessions";
import attendanceRouter from "./attendance";
import dashboardRouter from "./dashboard";
import examsRouter from "./exams";
import analyticsRouter from "./analytics";
import notificationsRouter from "./notifications";
import questionBankRouter from "./question-bank";
import studentProfileRouter from "./student-profile";
import homeworkRouter from "./homework";
import resourcesRouter from "./resources";
import studentPortalRouter from "./student-portal";
import reportsRouter from "./reports";
import paymentsRouter from "./payments";
import recordingsRoutesRouter from "./recordings-routes";
import publicRouter from "./public";
import adminSettingsRouter from "./admin-settings";
import flashcardsRouter from "./flashcards";
import coursesRouter from "./courses";
import centersRouter from "./centers";
import trialsRouter from "./trials";
import pastPapersRouter from "./past-papers";
import examGeneratorRouter from "./exam-generator";
import goalsRouter from "./goals";
import achievementsRouter from "./achievements";
import riskEngineRouter from "./risk-engine";
import onlineExamsRouter from "./online-exams";
import inventoryRouter from "./inventory";
import tutorialRouter from "./tutorial";
import timetableRouter from "./timetable";

const router: IRouter = Router();

router.use(authRouter);
router.use(changePasswordRouter);
router.use(healthRouter);
router.use(accountsRouter);
router.use(subjectsRouter);
router.use(studentsRouter);
router.use(sessionsRouter);
router.use(attendanceRouter);
router.use(dashboardRouter);
router.use(examsRouter);
router.use(analyticsRouter);
router.use(notificationsRouter);
router.use(questionBankRouter);
router.use(studentProfileRouter);
router.use(homeworkRouter);
router.use(resourcesRouter);
router.use(studentPortalRouter);
router.use(reportsRouter);
router.use(paymentsRouter);
router.use(recordingsRoutesRouter);
router.use(publicRouter);
router.use(adminSettingsRouter);
router.use(flashcardsRouter);
router.use(coursesRouter);
router.use(centersRouter);
router.use(trialsRouter);
router.use(pastPapersRouter);
router.use(examGeneratorRouter);
router.use(goalsRouter);
router.use(achievementsRouter);
router.use(riskEngineRouter);
router.use(onlineExamsRouter);
router.use(inventoryRouter);
router.use(tutorialRouter);
router.use(timetableRouter);

export default router;
