import { Router, type IRouter } from "express";
import healthRouter from "./health";
import { authRouter } from "./auth";
import changePasswordRouter from "./change-password";
import accountsRouter from "./accounts";
import subjectsRouter from "./subjects";
import { studentsRouter } from "./students";
import sessionsRouter from "./sessions";
import { attendanceRouter } from "./attendance";
import { dashboardRouter } from "./dashboard";
import examsRouter from "./exams";
import { analyticsRouter } from "./analytics";
import notificationsRouter from "./notifications";
import { questionBankRouter } from "./question-bank";
import studentProfileRouter from "./student-profile";
import { homeworkRouter } from "./homework";
import resourcesRouter from "./resources";
import studentPortalRouter from "./student-portal";
import reportsRouter from "./reports";
import paymentsRouter from "./payments";
import recordingsRoutesRouter from "./recordings-routes";
import publicRouter from "./public";
import adminSettingsRouter from "./admin-settings";
import { flashcardsRouter } from "./flashcards";
import centersRouter from "./centers";
import trialsRouter from "./trials";
import { pastPapersRouter } from "./past-papers";
import examGeneratorRouter from "./exam-generator";
import goalsRouter from "./goals";
import achievementsRouter from "./achievements";
import riskEngineRouter from "./risk-engine";
import onlineExamsRouter from "./online-exams";
import inventoryRouter from "./inventory";
import tutorialRouter from "./tutorial";
import timetableRouter from "./timetable";
import calendarRouter from "./calendar";
import gradebookRouter from "./gradebook";
import notifyBroadcastRouter from "./notify-broadcast";
import { lessonsRouter } from "./lessons";
import { subscriptionsRouter } from "./subscriptions";
import { mentorRouter } from "./mentor";
import { revisitRouter } from "./revisit";
import { ascendRouter } from "./ascend";
import { echoEvolveRouter } from "./echo-evolve";
import absenceNotifyRouter from "./absence-notify";
import { assistantsRouter } from "./assistants";
import { couponsRouter } from "./coupons";
import { landingSettingsRouter } from "./landing-settings";
import { notebooksRouter } from "./notebooks";
import { teacherVerificationRouter } from "./teacher-verification";
import { workspaceRouter } from "./workspace";
import { onboardingRouter } from "./onboarding";
import { settingsRouter } from "./settings";
import { semanticSearchRouter } from "./semantic-search";
import { autopilotRouter } from "./autopilot";
import { teacherCoursesRouter } from "./teacher-courses";
import { rubricsRouter } from "./rubrics";
import { messagesRouter } from "./messages";
import { tutorcraftRouter } from "./tutorcraft";
import { classforgeRouter } from "./classforge";
import studentFeedRouter from "./student-feed";
import focusCoachRouter from "./focus-coach";
import echoProfileRouter from "./echo-profile";
import peakRankingsRouter from "./peak-rankings";
import studyGroupsRouter from "./study-groups";
import studentMessagesThreadedRouter from "./student-messages-threaded";
import studentCalendarRouter from "./student-calendar";
import snapgradeRouter from "./snapgrade";
import trialVaultRouter from "./trial-vault";
import examVaultRouter from "./exam-vault";
import studentAnalyticsRouter from "./student-analytics";
import studentHomeSummaryRouter from "./student-home-summary";
import aiStatusRouter from "./ai-status";
import safetyRouter from "./safety";
import { weaveRouter } from "./weave";
import { coremindRouter } from "./coremind";
import { misconceptionsRouter } from "./misconceptions";
import { gradingRouter } from "./grading";
import { coremindAnalyticsRouter } from "./coremind-analytics";
import { parentAiRouter } from "./parent-ai";
import { assessmentHubRouter } from "./assessment-hub";
import { examSessionRouter } from "./exam-session";
import { assessmentGradingRouter } from "./assessment-grading";
import { certificationsRouter } from "./certifications";
import { assessmentExtrasRouter } from "./assessment-extras";
import { commThreadsRouter } from "./comm-threads";
import { commRoomsRouter } from "./comm-rooms";
import { commSupportRouter } from "./comm-support";
import { learningExperienceRouter } from "./learning-experience";
import { qaRouter } from "./qa";
import { phase14Router } from "./phase14";
import { contentEcosystemRouter } from "./content-ecosystem";
import { commerceRouter } from "./commerce";
import { revisionNotesRouter } from "./revision-notes";

const router: IRouter = Router();

router.use("/auth", authRouter);
router.use(changePasswordRouter);
router.use(healthRouter);
router.use(accountsRouter);
router.use(subjectsRouter);
router.use("/students", studentsRouter);
router.use(sessionsRouter);
router.use("/attendance", attendanceRouter);
router.use("/dashboard", dashboardRouter);
router.use(examsRouter);
router.use(analyticsRouter);
router.use(notificationsRouter);
router.use(questionBankRouter);
router.use(studentProfileRouter);
router.use(homeworkRouter);
router.use(resourcesRouter);
router.use(studentPortalRouter);
router.use(reportsRouter);
router.use(paymentsRouter);
router.use(recordingsRoutesRouter);
router.use(publicRouter);
router.use(adminSettingsRouter);
router.use(flashcardsRouter);
router.use(centersRouter);
router.use(trialsRouter);
router.use("/past-papers", pastPapersRouter);
router.use(examGeneratorRouter);
router.use(goalsRouter);
router.use(achievementsRouter);
router.use(riskEngineRouter);
router.use(onlineExamsRouter);
router.use(inventoryRouter);
router.use(tutorialRouter);
router.use(timetableRouter);
router.use(calendarRouter);
router.use(gradebookRouter);
router.use(notifyBroadcastRouter);
router.use("/lessons", lessonsRouter);
router.use("/subscriptions", subscriptionsRouter);
router.use("/mentor", mentorRouter);
router.use("/revisit", revisitRouter);
router.use("/ascend", ascendRouter);
router.use("/echo-evolve", echoEvolveRouter);
router.use("/absence-notify", absenceNotifyRouter);
router.use("/assistants", assistantsRouter);
router.use("/coupons", couponsRouter);
router.use(landingSettingsRouter);
router.use("/notebooks", notebooksRouter);
router.use("/teacher-verification", teacherVerificationRouter);
router.use("/workspace", workspaceRouter);
router.use("/onboarding", onboardingRouter);
router.use("/settings", settingsRouter);
router.use("/search", semanticSearchRouter);
router.use("/autopilot", autopilotRouter);
router.use(teacherCoursesRouter);
router.use(rubricsRouter);
router.use(messagesRouter);
router.use(tutorcraftRouter);
router.use(classforgeRouter);
router.use(studentFeedRouter);
router.use(focusCoachRouter);
router.use(echoProfileRouter);
router.use(peakRankingsRouter);
router.use(studyGroupsRouter);
router.use(studentMessagesThreadedRouter);
router.use(studentCalendarRouter);
router.use(snapgradeRouter);
router.use(trialVaultRouter);
router.use(examVaultRouter);
router.use(studentAnalyticsRouter);
router.use(studentHomeSummaryRouter);
router.use(aiStatusRouter);
router.use(safetyRouter);
router.use("/weave", weaveRouter);
router.use("/coremind", coremindRouter);
router.use(misconceptionsRouter);
router.use("/grading", gradingRouter);
router.use("/coremind", coremindAnalyticsRouter);
router.use(parentAiRouter);

// Phase 7 — Communication, Collaboration & Community Ecosystem
router.use(commThreadsRouter);
router.use(commRoomsRouter);
router.use(commSupportRouter);

// Phase 8 — Learning Experience, Content Delivery & Adaptive Personalization
router.use(learningExperienceRouter);

// Phase 6 — Assessment, Examination & Certification Ecosystem
router.use(assessmentHubRouter);
router.use("/exam-session", examSessionRouter);
router.use(assessmentGradingRouter);
router.use(certificationsRouter);
router.use(assessmentExtrasRouter);

// Phase 13 — Quality Assurance, Validation, Testing & Launch Readiness
router.use(qaRouter);

// Phase 14 — Platform Authenticity, Trust & Content Governance
router.use(phase14Router);

// Phase 15 — Educational Content Ecosystem
router.use(contentEcosystemRouter);

// Phase 16 — Commercialization & Business Operations
router.use(commerceRouter);
router.use(revisionNotesRouter);

export default router;

// Phase 11 governance router is registered in app.ts under /api/admin/governance
